### PR TITLE
Postgresql created_at, updated_at column data type changed.

### LINKED ISSUE #229: Definition file not visible on web UI when connected to PostgreSQL
**Describe the bug**
When connecting to PostgreSQL, the contents of the definition file are not displayed on the web UI screen.

**To Reproduce**
1. create definition file (Metrics).
2. run wave-autoscale
3. web UI > Metrics menu is empty

**Expected behavior**
definition data should be visible on the screen.

**Screenshots**
-

**Desktop (please complete the following information):**
 - 

**Smartphone (please complete the following information):**
 - 

**Additional context**
-

### PR DESCRIPTION
**Pull request by Ari-suhyeon**
## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] DevOps process (non-breaking change which improves efficiency and reliability for CI/CD)
- [ ] Documentation only

## What this PR does / why we need it:

When connecting to PostgreSQL, the contents of the definition file are not displayed on the web UI screen.
Postgresql column type changed due to type mismatch error.

## Which issue/s this PR fixes

fixes #229 

## How Has This Been Tested?

- definition data visible on web ui.

### CODE REVIEW

File: core/data-layer/src/data_layer.rs [hunk 1]
```diff
@@ -614,7 +614,7 @@ impl DataLayer {
         let metadata_string = serde_json::to_string(&scaling_component.metadata).unwrap();
         let query_string =
             "UPDATE scaling_component SET id=$1, component_kind=$2, metadata=$3, enabled=$4, updated_at=$5 WHERE db_id=$6";
-        let updated_at = Utc::now();
+        let updated_at = Utc::now().format("%Y-%m-%d %H:%M:%S").to_string();
```
Comment (pueding) [inline core/data-layer/src/data_layer.rs:617]: assert_eq!(dt.to_rfc3339_opts(SecondsFormat::Secs, true),
           "2018-01-26T18:30:09Z");

File: core/data-layer/src/data_layer.rs [hunk 2]
```diff
@@ -643,21 +643,21 @@ impl DataLayer {
             let metatdata_string = serde_json::to_string(&plan.metadata).unwrap();
             let query_string = "INSERT INTO plan (db_id, id, metadata, plans, enabled, created_at, updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT (id) DO UPDATE SET (metadata, plans, enabled, updated_at) = ($8, $9, $10, $11)";
             let id = Uuid::new_v4().to_string();
-            let updated_at = Utc::now();
+            let updated_at = Utc::now().format("%Y-%m-%d %H:%M:%S").to_string();
```
Comment (pueding) [inline core/data-layer/src/data_layer.rs:646]: assert_eq!(dt.to_rfc3339_opts(SecondsFormat::Secs, true),
           "2018-01-26T18:30:09Z");

File: core/data-layer/src/data_layer.rs [hunk 3]
```diff
@@ -785,7 +785,7 @@ impl DataLayer {
         let metatdata_string = serde_json::to_string(&plan.metadata).unwrap();
         let query_string =
             "UPDATE plan SET id=$1, metadata=$2, plans=$3, updated_at=$4, enabled=$5 WHERE db_id=$6";
-        let updated_at = Utc::now();
+        let updated_at = Utc::now().format("%Y-%m-%d %H:%M:%S").to_string();
```
Comment (pueding) [inline core/data-layer/src/data_layer.rs:788]: assert_eq!(dt.to_rfc3339_opts(SecondsFormat::Secs, true),
           "2018-01-26T18:30:09Z");

**Review by pueding — CHANGES_REQUESTED** [review]

**Review by pueding — APPROVED** [review]
